In [1]:
# Q 1
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
add_result = arr + 2
print("After adding 2:", add_result)
multiply_result = arr * 3
print("After multiplying by 3:", multiply_result)
divide_result = arr / 2
print("After dividing by 2:", divide_result)

After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


In [2]:
# Q 2
import numpy as np
# Reverse a NumPy array
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)
# Find the most frequent value and indices
def most_frequent(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_frequent_value = values[counts == max_count][0]
    indices = np.where(arr == most_frequent_value)[0]
    return most_frequent_value, indices
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_frequent_x, indices_x = most_frequent(x)
print("Most frequent value in x:", most_frequent_x, "at indices", indices_x)
most_frequent_y, indices_y = most_frequent(y)
print("Most frequent value in y:", most_frequent_y, "at indices", indices_y)

Reversed array: [5 4 6 3 2 1]
Most frequent value in x: 1 at indices [0 5 7 8 9]
Most frequent value in y: 1 at indices [0 1 2]


In [3]:
# Q 3
import numpy as np
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
# a) Access 1st row, 2nd column
element_1_2 = arr[0, 1]
print("Element at 1st row, 2nd column:", element_1_2)
# b) Access 3rd row, 1st column
element_3_1 = arr[2, 0]
print("Element at 3rd row, 1st column:", element_3_1)

Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


In [4]:
# Q 4
import numpy as np
# Create a 1-D NumPy array with evenly spaced 25 numbers from 10 to 100
my_array = np.linspace(10, 100, 25)
# Print array properties
dimensions = my_array.ndim
shape = my_array.shape
total_elements = my_array.size
data_type = my_array.dtype
total_bytes = my_array.nbytes
print("Dimensions:", dimensions)
print("Shape:", shape)
print("Total Elements:", total_elements)
print("Data Type:", data_type)
print("Total Bytes Consumed:", total_bytes)
# Find the transpose using reshape()
transposed_array = my_array.reshape(25, 1)
print("Transposed using reshape():\n", transposed_array)
# Checking transpose using T attribute
transposed_T = my_array.T
print("Transposed using T attribute:\n", transposed_T)
# Explanation: The T attribute does not work on 1-D arrays, as transposing a 1-D array does not change its shape.

Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes Consumed: 200
Transposed using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transposed using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [5]:
# Q 5
import numpy as np
# Create a 2-D array
ucs420_myname = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
# Compute statistical values
mean_value = np.mean(ucs420_myname)
median_value = np.median(ucs420_myname)
max_value = np.max(ucs420_myname)
min_value = np.min(ucs420_myname)
unique_elements = np.unique(ucs420_myname)
print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_elements)
# Reshape the array to 4 rows and 3 columns
reshaped_ucs420_myname = ucs420_myname.reshape(4, 3)
print("Reshaped Array (4x3):\n", reshaped_ucs420_myname)
# Resize the array to 2 rows and 3 columns
resized_ucs420_myname = np.resize(ucs420_myname, (2, 3))
print("Resized Array (2x3):\n", resized_ucs420_myname)


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
